### ISSUE TITLE
Implement math using numpy

### ISSUE THREAD

**Issue by Korijn** [almarklein/visvis2#4]
Since we depend on numpy anyway; we can use it in the math implementation

**Comment by almarklein** [comment]
There's one advantage of not using numpy for the internal math: it keeps the possibility open to export a visualization to JS. We do import numpy now, but that is to build arrays that eventually end up as buffers/texures in wgpu. We probably don't do any "numpy ops" on them.

So unless there are obvious benefits, and since the current code is already pure-Pythin, I'd prefer to keep it like that for the time being.

**Comment by Korijn** [comment]
agreed
